export default {
  dropdownTriangle: require('../assets/images/ic_dropdown.png'),
  fb: require('../assets/images/ic_facebook.png'),
  apple: require('../assets/images/ic_apple.png'),
  google: require('../assets/images/ic_google.png'),
  insta: require('../assets/images/ic_insta.png'),
  back: require('../assets/images/ic_back.png'),
  backWithSquare: require('../assets/images/backWithSquare.png'),
  tabAInActive: require('../assets/images/ic_home.png'),
  tabAActive: require('../assets/images/ic_homeactive.png'),
  tabBInActive: require('../assets/images/ic_offer.png'),
  tabBActive: require('../assets/images/ic_offeractive.png'),
  tabCActive: require('../assets/images/ic_brandactive.png'),
  tabCInActive: require('../assets/images/ic_brandsNew.png'),
  tabDInActive: require('../assets/images/ic_celebrity.png'),
  tabDActive: require('../assets/images/ic_celebrityactive.png'),
  tabEInActive: require('../assets/images/ic_profile.png'),
  tabEActive: require('../assets/images/ic_profileactive.png'),
  logo: require('../assets/images/ic-logo.png'),
  search: require('../assets/images/ic_search.png'),
  cartShop: require('../assets/images/ic_cartshop.png'),
  packageTransfer: require('../assets/images/ic_packagetransfer.png'),
  trackOrder: require('../assets/images/ic_read.png'),
  forwardCircle: require('../assets/images/ic_letsgo.png'),
  contactLess: require('../assets/images/ic_contactless.png'),
  filter: require('../assets/images/ic_filter.png'),
  locationSmall: require('../assets/images/ic_locationblack.png'),
  locationGreen: require('../assets/images/ic_locationgreen.png'),
  percentRed: require('../assets/images/ic_percent.png'),
  time: require('../assets/images/ic_time.png'),
  starWhite: require('../assets/images/ic_starwhite.png'),
  more: require('../assets/images/ic_more.png'),
  rightBlue: require('../assets/images/ic_goA.png'),
  icProfile: require('../assets/images/ic_profile1.png'),
  goRight: require('../assets/images/ic_go2.png'),
  message: require('../assets/images/ic_masg.png'),
  share: require('../assets/images/ic_share.png'),
  notifcation: require('../assets/images/ic_notification.png'),
  payment: require('../assets/images/ic_card.png'),
  fav: require('../assets/images/ic_fav1.png'),
  about: require('../assets/images/ic_about.png'),
  myOrder: require('../assets/images/ic_myorder.png'),
  allProducts: require('../assets/images/ic_all.png'),
  icCloths: require('../assets/images/ic_cloyhing.png'),
  favWhite: require('../assets/images/ic_heart.png'),
  whiteFilledHeart: require('../assets/images/ic_heartfilled.png'),
  blackFilledHeart: require('../assets/images/ic_heartfilled2.png'),
  bag: require('../assets/images/ic_bag.png'),
  camera: require('../assets/images/ic_camera.png'),
  done: require('../assets/images/ic_done.png'),
  lgDone: require('../assets/images/ic_done3.png'),
  work: require('../assets/images/ic_work.png'),
  home: require('../assets/images/ic_home2.png'),
  add: require('../assets/images/ic_add.png'),
  cart: require('../assets/images/ic_cart.png'),
  call: require('../assets/images/ic_call.png'),
  info: require('../assets/images/ic_info.png'),
  orderprofile: require('../assets/images/ic_profile2.png'),
  cross: require('../assets/images/ic_cross.png'),
  delete: require('../assets/images/ic_del.png'),
  notif: require('../assets/images/ic_notif.png'),
  contactIllustration: require('../assets/images/ic_img.png'),
  track: require('../assets/images/ic_track.png'),
  tick: require('../assets/images/ic_tick.png'),
  tick_black: require('../assets/images/ic_tick_black.png'),
  ic_package1: require('../assets/images/ic_package.png'),
  ic_package2: require('../assets/images/ic_package2.png'),
  ic_package3: require('../assets/images/ic_package3.png'),
  ic_package4: require('../assets/images/ic_package4.png'),
  ic_calendar: require('../assets/images/ic_calendar.png'),
  percent: require('../assets/images/ic_percent.png'),
  percent2: require('../assets/images/ic_percentage.png'),
  icUpload: require('../assets/images/ic_upload.png'),
  icInstruction: require('../assets/images/ic_instructions.png'),
  paymentMethod: require('../assets/images/ic_pay.png'),
  clientLogo: require('../assets/images/ic_logo.png'),
  cartActive: require('../assets/images/ic_cartactive.png'),
  cartInActive: require('../assets/images/ic_cartinactive.png'),
  // testImage: require('../assets/images/testImage.jpg'),
  radioInActive: require('../assets/images/ic_deselected.png'),
  radioActive: require('../assets/images/ic_selected.png'),
  settings: require('../assets/images/ic_settings.png'),
  tickBlack: require('../assets/images/ic_tick_black.png'),
  tickWhite: require('../assets/images/ic_tick2.png'),
  wallet: require('../assets/images/ic_wallet.png'),
  sort: require('../assets/images/ic_sort_inactive.png'),
  filterSelected: require('../assets/images/ic_filter_2.png'),
  crossBlue: require('../assets/images/ic_cross_blue.png'),
  sortSelected: require('../assets/images/ic_sort_active.png'),
  sideUpwordArrow: require('../assets/images/ic_arrow.png'),
  crossBlueB: require('../assets/images/ic_cross_2.png'),
  masterCard: require('../assets/images/mastercard.png'),
  emptyCart: require('../assets/images/ic_emptycart.png'),
  noDataFound: require('../assets/images/RoyoorderNewImages/ic_nostores1.png'),
  twitterIcon: require('../assets/images/ic_twitter.png'),
  successfulIcon: require('../assets/images/ic_successful.png'),
  deleteRed: require('../assets/images/ic_delete.png'),
  editBlue: require('../assets/images/ic_edit.png'),
  crossB: require('../assets/images/ic_close_4.png'),
  icClose3: require('../assets/images/ic_close_3.png'),
  icClose4: require('../assets/images/ic_close4.png'),
  check: require('../assets/images/ic_check.png'),
  unCheck: require('../assets/images/ic_uncheck.png'),
  workActive: require('../assets/images/ic_work_active.png'),
  workInActive: require('../assets/images/ic_work_unactice.png'),
  emptyCart2: require('../assets/images/ic_empty-card.png'),
  noDataFound2: require('../assets/images/ic_placeholderbeeNew.png'),
  noDataFound3: require('../assets/images/noDataFound.png'),

  icCamIcon: require('../assets/images/ic_capture.png'),
  icRemoveIcon: require('../assets/images/ic_remove_product.png'),
  noOffers: require('../assets/images/ic_nooffers.png'),

  //CARLITOOICONS
  carlitoLogo: require('../assets/images/CARLITOO/CARLITOO_TEXT_logo.png'),
  drawerMenuIcon: require('../assets/images/CARLITOO/menu.png'),
  profileSettingIcon: require('../assets/images/CARLITOO/profile-user.png'),
  searchIcon: require('../assets/images/CARLITOO/loupe.png'),
  upperSectionMain: require('../assets/images/CARLITOO/uppersection.png'),
  carlitooFace: require('../assets/images/CARLITOO/carlitoo_face.png'),
  foodIcon: require('../assets/images/CARLITOO/FOOD.png'),
  giftIcon: require('../assets/images/CARLITOO/GIFT.png'),
  shopIcon: require('../assets/images/CARLITOO/SHOP.png'),
  taxiIcon: require('../assets/images/CARLITOO/TAXI.png'),
  pickUpIcon: require('../assets/images/CARLITOO/PICK_UP.png'),
  pharmaIcon: require('../assets/images/CARLITOO/PHARMACY.png'),

  //VendorApp
  backArrow: require('../assets/images/VendorAppImages/back_ico.png'),
  editPencilIcon: require('../assets/images/VendorAppImages/edit.png'),
  icoLocation: require('../assets/images/VendorAppImages/ico_allocation.png'),
  icoDropDownArrow: require('../assets/images/VendorAppImages/ico_arrow.png'),
  redCross: require('../assets/images/VendorAppImages/ico_close_red.png'),
  greyCrossSmall: require('../assets/images/VendorAppImages/ico_close.png'),
  dropDownSingle: require('../assets/images/VendorAppImages/ico_dropdown.png'),
  icoEditWhite: require('../assets/images/VendorAppImages/ico_edit_white.png'),
  icoGeoFence: require('../assets/images/VendorAppImages/ico_geofence.png'),
  icoImage: require('../assets/images/VendorAppImages/ico_image.png'),
  infoIcon: require('../assets/images/VendorAppImages/ico_info.png'),
  logout: require('../assets/images/VendorAppImages/ico_logout.png'),
  whiteMenu: require('../assets/images/VendorAppImages/ico_menu_white.png'),
  redMenu: require('../assets/images/VendorAppImages/ico_menu.png'),
  icoNonveg: require('../assets/images/VendorAppImages/ico_nonveg.png'),
  icoNotification: require('../assets/images/VendorAppImages/ico_notification.png'),
  icoTimeOrder: require('../assets/images/VendorAppImages/ico_order_time.png'),
  icoSelectOrderActive: require('../assets/images/VendorAppImages/ic_order_active.png'),
  icoSelectOrderInactive: require('../assets/images/VendorAppImages/ic_order_unactive.png'),
  icoSelectProductActive: require('../assets/images/VendorAppImages/ic_product_active.png'),
  icoSelectProductInActive: require('../assets/images/VendorAppImages/ic_product_unactive.png'),
  icoProfileInactive: require('../assets/images/VendorAppImages/ico_profile.png'),
  icoRadioSelected: require('../assets/images/VendorAppImages/ico_radio_selected.png'),
  icoRadioNonSelected: require('../assets/images/VendorAppImages/ico_radio.png'),
  icoRevenueSelected: require('../assets/images/VendorAppImages/ic_revenue_active.png'),
  icoRevenueNonSelected: require('../assets/images/VendorAppImages/ic_revenue_unactive.png'),
  splashLogoLogin: require('../assets/images/VendorAppImages/ico_royo_orser_logo_login.png'),
  splashLogoSplash: require('../assets/images/VendorAppImages/ico_royo_orser_logo_splash.png'),
  icoSearch: require('../assets/images/VendorAppImages/ico_search.png'),
  icoVeg: require('../assets/images/VendorAppImages/ico_veg.png'),
  icoOneByOne: require('../assets/images/VendorAppImages/onebyone_img.png'),
  gridViewIcon: require('../assets/images/VendorAppImages/ico_Grid.png'),
  listViewIcon: require('../assets/images/VendorAppImages/ico_list.png'),
  iconAmount: require('../assets/images/VendorAppImages/ic_amount.png'),
  iconItems: require('../assets/images/VendorAppImages/ic_items.png'),
  iconPayments: require('../assets/images/VendorAppImages/ic_payment.png'),
  myStoreIcon: require('../assets/images/VendorAppImages/ic_my_store.png'),
  icCheck1: require('../assets/images/VendorAppImages/ic_check1.png'),
  icCheck2: require('../assets/images/VendorAppImages/ic_check2.png'),
  icCross2: require('../assets/images/VendorAppImages/ic_cross.png'),
  icDelete: require('../assets/images/VendorAppImages/ic_del.png'),
  icDropdown: require('../assets/images/VendorAppImages/ic_down.png'),
  icImage: require('../assets/images/VendorAppImages/ic_image.png'),
  icPlaceholder: require('../assets/images/VendorAppImages/ic_placeholder.png'),
  icToggleoff: require('../assets/images/VendorAppImages/ic_toggleoff.png'),
  icToggleon: require('../assets/images/VendorAppImages/ic_toggleon.png'),
  icUpArrow: require('../assets/images/VendorAppImages/ic_up.png'),

  icAttachments: require('../assets/images/ic_attachment.png'),
  frameorder: require('../assets/images/Courier/Frameorder.png'),
  backArrowCourier: require('../assets/images/Courier/Back_Arrow.png'),
  openBox: require('../assets/images/Courier/Open_Box.png'),
  bmi: require('../assets/images/Courier/BMI.png'),
  radioLocation: require('../assets/images/Courier/Radio.png'),
  locationCourier: require('../assets/images/Courier/Locationg.png'),
  searchIcon2: require('../assets/images/Courier/Frame_310.png'),
  mapPin2: require('../assets/images/Courier/pin.png'),
  mapPin3: require('../assets/images/Courier/destination.png'),
  cabImage: require('../assets/images/Courier/cab.png'),
  checkbox: require('../assets/images/Courier/Checkbox.png'),
  inactive_checkbox: require('../assets/images/Courier/ic_inactive2.png'),
  toolTip: require('../assets/images/Courier/info.png'),
  user: require('../assets/images/Courier/user.png'),
  briefcase: require('../assets/images/Courier/briefcase.png'),
  chev_down: require('../assets/images/Courier/chev_down.png'),
  cabLarge: require('../assets/images/Courier/image_6.png'),
  closeButton: require('../assets/images/Courier/Close.png'),
  plus: require('../assets/images/Courier/plus.png'),
  driver: require('../assets/images/Courier/blue_ripple.gif'),
  patternOne: require('../assets/images/ic_pattern1.png'),
  patternTwo: require('../assets/images/ic_pattern2.png'),
  star: require('../assets/images/ic_star.png'),
  filterNew: require('../assets/images/ic_filter1.png'),
  wallet2: require('../assets/images/ic_wallet2.png'),
  time2: require('../assets/images/ic_time2.png'),
  heart2: require('../assets/images/ic_heart2.png'),
  slider: require('../assets/images/ic_slider.png'),
  nature: require('../assets/images/nature.jpeg'),
  tick2: require('../assets/images/ic_tick_2.png'),
  homeActive: require('../assets/images/ic_homeblue.png'),
  homeInActive: require('../assets/images/ic_homedull.png'),
  ordersActive: require('../assets/images/ic_ordeer.png'),
  ordersInActive: require('../assets/images/ic_orderdull.png'),
  profileActive: require('../assets/images/ic_profileblue.png'),
  profileInActive: require('../assets/images/ic_accountdull.png'),
  bronze: require('../assets/images/ic_bronze.png'),
  gold: require('../assets/images/ic_gold.png'),
  platinum: require('../assets/images/ic_platinum.png'),
  silver: require('../assets/images/ic_silver.png'),
  totalLoyaltyBackground: require('../assets/images/ic_total.png'),
  ic_google2: require('../assets/images/ic_google2.png'),
  ic_fb2: require('../assets/images/ic_fb2.png'),
  ic_apple2: require('../assets/images/ic_apple2.png'),
  ic_twitter2: require('../assets/images/ic_twitter2.png'),
  ic_apple: require('../assets/images/ic_apple.png'),
  accountActive: require('../assets/images/ic_account2.png'),
  accountInActive: require('../assets/images/ic_account1.png'),
  brandsActive: require('../assets/images/ic_brands2.png'),
  brandInActive: require('../assets/images/ic_brand1.png'),
  cart2Active: require('../assets/images/ic_cart2.png'),
  cart2InActive: require('../assets/images/ic_cart1.png'),
  celebActive: require('../assets/images/ic_celeb2.png'),
  celebInActive: require('../assets/images/ic_celeb1.png'),
  home2Active: require('../assets/images/ic_home3.png'),
  home2InActive: require('../assets/images/ic_house1.png'),
  delivery: require('../assets/images/ic_delivery.png'),
  redLocation: require('../assets/images/ic_location.png'),
  location2: require('../assets/images/ic_location2.png'),
  icDotedLine: require('../assets/images/dottedLine.png'),
  homeRedActive: require('../assets/images/ic_home4.png'),
  homeRedInActive: require('../assets/images/ic_home_black4.png'),
  cartRedActive: require('../assets/images/ic_cart4.png'),
  cartRedInActive: require('../assets/images/ic_cart_black4.png'),
  ordersRedActive: require('../assets/images/ic_orders2.png'),
  ordersRedInActive: require('../assets/images/ic_orders1.png'),
  accountRedActive: require('../assets/images/ic_account_red.png'),
  accountRedInActive: require('../assets/images/ic_account3.png'),
  search1: require('../assets/images/ic_search1.png'),
  search2: require('../assets/images/orbitAssets/ic_search3.png'),
  backArrow1: require('../assets/images/ic_back1.png'),
  filter1: require('../assets/images/filter_ico.png'),
  greyRoundSearch: require('../assets/images/ic_search_round.png'),
  greyRoundBack: require('../assets/images/ic_back_round.png'),
  greyRoundPlus: require('../assets/images/ic_plus.png'),
  startwo: require('../assets/images/ic_star_2.png'),
  backRound2: require('../assets/images/ic_back_round_2.png'),
  searchRound2: require('../assets/images/ic_search_2.png'),

  ic_add: require('../assets/images/ic_add_new_location.png'),
  ic_cross: require('../assets/images/ic_backwd_dark.png'),
  dark: require('../assets/images/ic_dark.png'),
  light: require('../assets/images/ic_light.png'),
  dropDownNew: require('../assets/images/ic_drpdwn.png'),
  icBackb: require('../assets/images/ic_back_b.png'),
  icSearchb: require('../assets/images/ic_search_b.png'),
  icShareb: require('../assets/images/ic_share_b.png'),
  icVeg: require('../assets/images/ic_veg.png'),
  icNonVeg: require('../assets/images/ic_nonveg.png'),

  dineIn: require('../assets/images/ic_dine.png'),
  dineInInActive: require('../assets/images/ic_dine1.png'),
  takeaway: require('../assets/images/ic_takeaway.png'),
  takeawayInActive: require('../assets/images/ic_take1.png'),
  radioNewActive: require('../assets/images/ic_radio.png'),
  radioNewInActive: require('../assets/images/ic_radio1.png'),
  deliveryInActive: require('../assets/images/ic_delivery1.png'),
  crossC: require('../assets/images/ic_crossNew.png'),
  icGo: require('../assets/images/ic_go.png'),
  icUp: require('../assets/images/ic_up.png'),

  //gif images
  search_gif: require('../assets/images/gif/search.gif'),
  cart_gif: require('../assets/images/gif/emptycart.gif'),

  //Tracking images
  acceptActive: require('../assets/images/TrackOrderImages/ic_accepted1.png'),
  acceptInactive: require('../assets/images/TrackOrderImages/ic_accepted2.png'),

  deliverActive: require('../assets/images/TrackOrderImages/ic_delivered1.png'),
  deliverInactive: require('../assets/images/TrackOrderImages/ic_delivered2.png'),

  onmywayActive: require('../assets/images/TrackOrderImages/ic_onway1.png'),
  onmywayInactive: require('../assets/images/TrackOrderImages/ic_onway2.png'),

  processingActive: require('../assets/images/TrackOrderImages/ic_processing1.png'),
  processingInactive: require('../assets/images/TrackOrderImages/ic_processing2.png'),
  icScooter: require('../assets/images/TrackOrderImages/ic_scooter.png'),
  icDestination: require('../assets/images/ic_destination.png'),
  gifImg: require('../assets/images/5ef9d70b03d22b1acd145b9422d3a33f.gif'),
  // 5ef9d70b03d22b1acd145b9422d3a33f.gif

  //royoorder new images
  wishlist: require('../assets/images/RoyoorderNewImages/ic_wishlist.png'),
  share1: require('../assets/images/RoyoorderNewImages/ic_share.png'),
  contactUs: require('../assets/images/RoyoorderNewImages/ic_contact.png'),
  settings1: require('../assets/images/RoyoorderNewImages/ic_settings.png'),
  links: require('../assets/images/RoyoorderNewImages/ic_links.png'),
  myOrder2: require('../assets/images/RoyoorderNewImages/ic_orders.png'),
  loyalty: require('../assets/images/RoyoorderNewImages/ic_loyalty.png'),
  wallet3: require('../assets/images/RoyoorderNewImages/ic_wallet.png'),
  mystores2: require('../assets/images/RoyoorderNewImages/ic_stores.png'),
  subscription: require('../assets/images/RoyoorderNewImages/ic_sub.png'),
  recently_search: require('../assets/images/RoyoorderNewImages/ic_recent.png'),
  trending: require('../assets/images/RoyoorderNewImages/ic_trending.png'),
  icMark1: require('../assets/images/RoyoorderNewImages/ic_mark1.png'),
  icMark2: require('../assets/images/RoyoorderNewImages/ic_mark2.png'),
  icStarIcon: require('../assets/images/RoyoorderNewImages/ic_starIcon.png'),
  ic_timeIcon: require('../assets/images/RoyoorderNewImages/ic_timeIcon.png'),
  ic_pinIcon: require('../assets/images/RoyoorderNewImages/ic_pinIcon.png'),
  ic_offersIcon: require('../assets/images/RoyoorderNewImages/ic_offersIcon.png'),
  ic_nonveg: require('../assets/images/RoyoorderNewImages/ic_nonveg.png'),
  ic_veg: require('../assets/images/RoyoorderNewImages/ic_veg.png'),

  icTime2: require('../assets/images/RoyoorderNewImages/ic_time.png'),
  icBrandActive: require('../assets/images/RoyoorderNewImages/ic_tag2.png'),
  icBrandInActive: require('../assets/images/RoyoorderNewImages/ic_tag.png'),
  icCelebActive: require('../assets/images/RoyoorderNewImages/ic_celeb2.png'),
  icCelebInActive: require('../assets/images/RoyoorderNewImages/ic_celeb1.png'),
  icRedPhone: require('../assets/images/RoyoorderNewImages/Group24.png'),
  icLocation1: require('../assets/images/RoyoorderNewImages/ic_location1.png'),
  icRedOval: require('../assets/images/RoyoorderNewImages/ic_oval2.png'),
  icRedChecked: require('../assets/images/RoyoorderNewImages/ic_checked.png'),
  icUnChecked: require('../assets/images/RoyoorderNewImages/ic_unchecked.png'),
  currentLocation: require('../assets/images/RoyoorderNewImages/ic_current.png'),
  icMap: require('../assets/images/RoyoorderNewImages/ic_map.png'),
  icCelebActive1: require('../assets/images/ic_celeb3.png'),
  icCelebInActive1: require('../assets/images/ic_celebGrey1.png'),
  brandsActive1: require('../assets/images/ic_tag1.png'),
  brandsInActive1: require('../assets/images/ic_tagGrey1.png'),
  taxiUserAccount: require('../assets/images/TAXIAPPIMAGES/ic_account.png'),
  savedLocationImage: require('../assets/images/TAXIAPPIMAGES/ic_fav.png'),
  noRides: require('../assets/images/TAXIAPPIMAGES/ic_norides.png'),
  RecentLocationImage: require('../assets/images/TAXIAPPIMAGES/ic_saved.png'),
  mapNavigation: require('../assets/images/TAXIAPPIMAGES/ic_nav.png'),
  locationPin: require('../assets/images/TAXIAPPIMAGES/ic_pin.png'),
  soptLight: require('../assets/images/TAXIAPPIMAGES/ic_soptlight.png'),
  markerPin2: require('../assets/images/TAXIAPPIMAGES/ic_pin4.png'),
  icGold1: require('../assets/images/RoyoorderNewImages/ic_gold1.png'),
  icGold2: require('../assets/images/RoyoorderNewImages/ic_gold2.png'),
  icPlatinum1: require('../assets/images/RoyoorderNewImages/ic_platinum1.png'),
  icPlatinum2: require('../assets/images/RoyoorderNewImages/ic_platinum2.png'),
  icSilver1: require('../assets/images/RoyoorderNewImages/ic_silver1.png'),
  icSilver2: require('../assets/images/RoyoorderNewImages/ic_silver2.png'),
  icBronze1: require('../assets/images/RoyoorderNewImages/ic_bronze1.png'),
  icBronze2: require('../assets/images/RoyoorderNewImages/ic_bronze2.png'),
  icActiveRadio: require('../assets/images/RoyoorderNewImages/ic_radio2.png'),
  icInActiveRadio: require('../assets/images/RoyoorderNewImages/ic_radio1.png'),
  icCheckBoxActive: require('../assets/images/RoyoorderNewImages/ic_checked2.png'),
  icCheckBoxInactive: require('../assets/images/RoyoorderNewImages/ic_unchecked2.png'),
  newfilter: require('../assets/images/RoyoorderNewImages/ic_filter.png'),
  newsort: require('../assets/images/RoyoorderNewImages/sort.png'),
  icBagA: require('../assets/images/RoyoorderNewImages/ic_bag2.png'),
  cartIcon: require('../assets/images/RoyoorderNewImages/ic_cart.png'),
  icLocationPin_: require('../assets/images/RoyoorderNewImages/ic_location_.png'),

  cash: require('../assets/images/TAXIAPPIMAGES/ic_cash.png'),
  card: require('../assets/images/TAXIAPPIMAGES/ic_card.png'),
  upi: require('../assets/images/TAXIAPPIMAGES/ic_upi.png'),
  close2: require('../assets/images/TAXIAPPIMAGES/ic_close1.png'),
  calendarA: require('../assets/images/TAXIAPPIMAGES/ic_calendar2.png'),
  calendarB: require('../assets/images/TAXIAPPIMAGES/ic_calendar.png'),
  icTime: require('../assets/images/TAXIAPPIMAGES/ic_time.png'),
  discount2: require('../assets/images/TAXIAPPIMAGES/ic_discount.png'),

  icgo2: require('../assets/images/TAXIAPPIMAGES/ic_go2.png'),
  locationpin3: require('../assets/images/TAXIAPPIMAGES/ic_pin3.png'),
  locationpinGreen: require('../assets/images/TAXIAPPIMAGES/ic_pingreen.png'),
  icgo3: require('../assets/images/TAXIAPPIMAGES/ic_go.png'),
  icEmptyCart: require('../assets/images/RoyoorderNewImages/ic_emptycart2.png'),
  icEmptyCartA: require('../assets/images/RoyoorderNewImages/ic_emptycart3.png'),
  icEmptyCartB: require('../assets/images/RoyoorderNewImages/ic_emptygrey.png'),
  icEmptyCartC: require('../assets/images/RoyoorderNewImages/Group8.png'),
  icEmptyCartD: require('../assets/images/RoyoorderNewImages/ic_placeholderbee.png'),
  car3: require('../assets/images/TAXIAPPIMAGES/ic_car3.png'),
  icStar3: require('../assets/images/RoyoorderNewImages/ic_star3.png'),
  icEdit1: require('../assets/images/RoyoorderNewImages/ic_edit1.png'),

  // royo order tab
  activeRoyo: require('../assets/images/royoTab/ic_active.png'),
  cancelledRoyo: require('../assets/images/royoTab/ic_cancelled.png'),
  deliveredRoyo: require('../assets/images/royoTab/ic_deliverd.png'),
  logoRoyo: require('../assets/images/royoTab/ic_logo.png'),
  timerRoyo: require('../assets/images/royoTab/ic_pensinf.png'),
  warningRoyo: require('../assets/images/royoTab/ic_warning.png'),
  inStockRoyo: require('../assets/images/royoTab/ic_on.png'),
  outStockRoyo: require('../assets/images/royoTab/ic_off.png'),
  editRoyo: require('../assets/images/royoTab/ic_edit.png'),
  deleteRoyo: require('../assets/images/royoTab/ic_delete.png'),
  selectedRoyo: require('../assets/images/royoTab/ic_select.png'),
  deselectedRoyo: require('../assets/images/royoTab/ic_deselect.png'),
  viseCardRoyo: require('../assets/images/royoTab/ic_visa.png'),
  masterCardRoyo: require('../assets/images/royoTab/ic_mastercard.png'),
  backRoyo: require('../assets/images/royoTab/ic_back.png'),
  whatsAppRoyo: require('../assets/images/royoTab/ic_wa.png'),
  callRoyo: require('../assets/images/royoTab/ic_call.png'),
  shareRoyo: require('../assets/images/royoTab/ic_share.png'),
  emptyCartRoyo: require('../assets/images/royoTab/ic_epmtycart.png'),
  closeRoyo: require('../assets/images/royoTab/ic_close.png'),
  onlineRoyo: require('../assets/images/royoTab/ic_online.png'),
  offlineRoyo: require('../assets/images/royoTab/ic_offline.png'),

  accountActiveRoyo: require('../assets/images/royoTab/ic_account2.png'),
  accountInactiveRoyo: require('../assets/images/royoTab/ic_account1.png'),
  homeActiveRoyo: require('../assets/images/royoTab/ic_home2.png'),
  homeInactiveRoyo: require('../assets/images/royoTab/ic_homwe2.png'),
  productActiveRoyo: require('../assets/images/royoTab/ic_products2.png'),
  productInactiveRoyo: require('../assets/images/royoTab/ic_products1.png'),
  orderActiveRoyo: require('../assets/images/royoTab/ic_orders.png'),
  orderInActiveRoyo: require('../assets/images/royoTab/ic_orders1.png'),
  signoutRoyo: require('../assets/images/royoTab/ic_signout.png'),
  transactionsRoyo: require('../assets/images/royoTab/ic_transactions.png'),
  edit1Royo: require('../assets/images/royoTab/Shape.png'),
  paymentSettinRoyo: require('../assets/images/royoTab/ic_paysettings.png'),
  cameraRoyo: require('../assets/images/royoTab/ic_camera2.png'),

  testingImageRoyo: require('../assets/images/royoTab/Food-Pizza-Basil-Tomato-removebg-preview.png'),
  printer: require('../assets/images/RoyoorderNewImages/ic_print.png'),
  bluetooth: require('../assets/images/RoyoorderNewImages/bluetooth.png'),
  rightArrowAngle: require('../assets/images/RoyoorderNewImages/right-arrow-angle.png'),
  car5: require('../assets/images/TAXIAPPIMAGES/ic_car1.png'),
  ride: require('../assets/images/TAXIAPPIMAGES/ic_ride.png'),
  taxiOrders: require('../assets/images/TAXIAPPIMAGES/ic_orders.png'),
  icAdd: require('../assets/images/TAXIAPPIMAGES/ic_add.png'),
  icNearby: require('../assets/images/TAXIAPPIMAGES/ic_nearby.png'),
  icRemove: require('../assets/images/TAXIAPPIMAGES/ic_remove.png'),
  locationRoundedBackground: require('../assets/images/TAXIAPPIMAGES/ic_location.png'),
  starRoundedBackground: require('../assets/images/TAXIAPPIMAGES/ic_star.png'),
  clock: require('../assets/images/TAXIAPPIMAGES/ic_clock.png'),
  grayDot: require('../assets/images/TAXIAPPIMAGES/ic_dot.png'),
  blackSquare: require('../assets/images/TAXIAPPIMAGES/ic_square.png'),
  blackNav: require('../assets/images/TAXIAPPIMAGES/ic_nav.png'),
  rideFilled: require('../assets/images/TAXIAPPIMAGES/ic_ridefilled.png'),

  plushRoundedBackground: require('../assets/images/TAXIAPPIMAGES/ic_plus.png'),
  icViewMore: require('../assets/images/RoyoorderNewImages/ic_viewmore.png'),
  msg: require('../assets/images/ic_msg.png'),
  call2: require('../assets/images/ic_call2.png'),

  inviteFriend: require('../assets/images/orbitAssets/ic_invite.png'),
  changeLanguage: require('../assets/images/orbitAssets/ic_changelang.png'),
  myOrders: require('../assets/images/orbitAssets/ic_myotrders.png'),
  saved: require('../assets/images/orbitAssets/ic_saved.png'),
  roundPercentage: require('../assets/images/orbitAssets/ic_paymentmethods.png'),

  twoFinderOnBoard: require('../assets/images/TowFinder/ic_onboard.png'),
  facebook: require('../assets/images/TowFinder/ic_fb.png'),
  settings_icon: require('../assets/images/TowFinder/settings.png'),
  settings_red_icon: require('../assets/images/TowFinder/ic_settings1.png'),
  ic_cameraColored: require('../assets/images/ic_cameraColored.png'),
  pickUpSchedule: require('../assets/images/ic_pickup.png'),
  dropOffSchedule: require('../assets/images/ic_order.png'),
  icMyRideActive: require('../assets/images/ic_ride2.png'),
  icMyRideInActive: require('../assets/images/ic_ride1.png'),
  icShowPassword: require('../assets/images/ic_view1.png'),
  icHidePassword: require('../assets/images/ic_view2.png'),
  icImageUpload: require('../assets/images/ic_imgupload.png'),
  icGiftIcon: require('../assets/images/ic_gift.png'),
  mapIcon: require('../assets/images/ic_map.png'),

  inactiveaccept: require('../assets/images/vendorStatusImages/ic_inactiveaccept.png'),
  inactiveprocceing: require('../assets/images/vendorStatusImages/ic_inactiveprocceing.png'),
  inactiveoutdelivery: require('../assets/images/vendorStatusImages/ic_inactiveoutdelivery.png'),
  inactivedelivered: require('../assets/images/vendorStatusImages/ic_inactivedelivered.png'),

  support: require('../assets/images/ic_support.png'),
  checkBox2Active: require('../assets/images/ic_check2.png'),
  checkBox2InActive: require('../assets/images/ic_check1.png'),
  emptyCart3: require('../assets/images/emptyCart3.png'),
  markerPin: require('../assets/images/markerPin.png'),
  emptycartco: require('../assets/images/emptycartco.png'),

  icContactus: require('../assets/images/RoyoorderNewImages/ic_contactus.png'),
  icInventory: require('../assets/images/RoyoorderNewImages/ic_inventory.png'),
  icSales: require('../assets/images/RoyoorderNewImages/ic_sales.png'),
  icMinus: require('../assets/images/RoyoorderNewImages/ic_minus.png'),
  icStore: require('../assets/images/RoyoorderNewImages/ic_store.png'),
  icStore2: require('../assets/images/RoyoorderNewImages/ic_store2.png'),
  icPlus2: require('../assets/images/RoyoorderNewImages/ic_plus2.png'),
  icCross1: require('../assets/images/ic_cross1.png'),
  ordersucess: require('../assets/images/ordersucess.png'),
  icAdd1: require('../assets/images/RoyoorderNewImages/ic_add1.png'),
  icUp1: require('../assets/images/RoyoorderNewImages/ic_up.png'),
  icImagePlaceholder: require('../assets/images/VendorAppImages/ic_image1.png'),
  notrcukImage: require('../assets/images/ic_notrucks.png'),
  activeTruck: require('../assets/images/ic_truck2.png'),
  inactiveTruck: require('../assets/images/ic_truck1.png'),
  icMic: require('../assets/images/ic_mic.png'),
  icVoice: require('../assets/images/icVoice.png'),
  icDropdown4: require('../assets/images/ic_drpdwn4.png'),
  icMegaSafe: require('../assets/images/ic_label.png'),
  icPhoto: require('../assets/images/ic_photo.png'),
  icAdd4: require('../assets/images/ic_add2.png'),
  icMinus2: require('../assets/images/ic_minus.png'),

  // Book a Friend Images
  addFriend: require('../assets/images/BookAFriend/ic_add.png'),
  addRider: require('../assets/images/BookAFriend/ic_addrider.png'),
  closeFriendList: require('../assets/images/BookAFriend/ic_addrider.png'),
  selectFriendList: require('../assets/images/BookAFriend/ic_drpdwn.png'),
  riderImage: require('../assets/images/ic_profilegrey.png'),

  icCar: require('../assets/images/ic_topviewcar.png'),

  icSos: require('../assets/images/RoyoorderNewImages/ic_sos.png'),
  subscribe: require('../assets/images/subscribe.png'),
  icNoDrivers: require('../assets/images/RoyoorderNewImages/ic_nodrivers.png'),
  icLocationBlue: require('../assets/images/RoyoorderNewImages/ic_location_blue.png'),
  icInstagram: require('../assets/images/RoyoorderNewImages/ic_instagram.png'),
  icAddPlaceholder: require('../assets/images/RoyoorderNewImages/ic_placeholder.png'),
  icPrescription: require('../assets/images/RoyoorderNewImages/ic_pres.png'),
  icBikeMarker: require('../assets/images/TrackOrderImages/ic_bike.png'),
  icCross18: require('../assets/images/ic_18.png'),
  send: require('../assets/images/ic_send.png'),
  icBgLight: require('../assets/images/ic_lightbg.png'),
  icBgDark: require('../assets/images/ic_darkbg.png'),
  icDriverChat: require('../assets/images/ic_driver.png'),
  icStoreChat: require('../assets/images/ic_store.png'),
  icBikeMarker1: require('../assets/images/mapMarkers/ic_bike.png'),
  iccycleMarker: require('../assets/images/mapMarkers/ic_cycle.png'),
  icmanMarker: require('../assets/images/mapMarkers/ic_man.png'),
  ictruckMarker: require('../assets/images/mapMarkers/ic_truck.png'),
  icUserChat: require('../assets/images/ic_userchat.png'),
  icVendorChat: require('../assets/images/ic_vendorchat.png'),
  icOtherAddressType: require('../assets/images/RoyoorderNewImages/ic_other_address.png'),

  timer: require('../assets/images/timer.png'),
  icSocialShare: require('../assets/images/RoyoorderNewImages/social-media.png'),
  app_icon: require('../assets/images/app_icon_zonesso.png'),
  back1: require('../assets/images/back.png'),
  phone_button: require('../assets/images/phone_button.png'),
  gmail: require('../assets/images/gmail.png'),
  // facebook: require("../assets/images/facebook.png"),
  apple1: require('../assets/images/Apple.png'),
  location1: require('../assets/images/ic_location1.png'),
  check3: require('../assets/images/ic_check3.png'),
  search3: require('../assets/images/ic_search3.png'),
  back2: require('../assets/images/ic_back2.png'),
  heart3: require('../assets/images/ic_heart3.png'),
  heart4: require('../assets/images/ic_heart4.png'),
  back_dark: require('../assets/images/ic_back_dark.png'),
  icRefundable: require('../assets/images/refundable.png'),
  post: require('../assets/images/ic_post.png'),
  post_active: require('../assets/images/ic_post_active.png'),

  //p2p
  icP2pMore: require('../assets/images/p2p/ic_more.png'),
  icCallP2p: require('../assets/images/p2p/ic_call_p2p.png'),
  icAddPostP2p: require('../assets/images/p2p/ic_add_post.png'),
  icHomeP2p: require('../assets/images/p2p/ic_home_new.png'),
  icHomeP2pInActive: require('../assets/images/p2p/ic_home_new1.png'),
  icAccountP2p: require('../assets/images/p2p/ic_account_new.png'),
  icCartP2p: require('../assets/images/p2p/ic_cart_new.png'),
  icChatP2p: require('../assets/images/p2p/ic_chat_new.png'),
  icAccountP2pInActive: require('../assets/images/p2p/ic_account_new1.png'),
  icCartP2pInActive: require('../assets/images/p2p/ic_cart_new1.png'),
  icChatP2pInActive: require('../assets/images/p2p/ic_chat_new1.png'),
  icDefaultImg: require('../assets/images/p2p/default_image.jpg'),
  icMyPosts: require('../assets/images/p2p/ic_my_posts.png'),
  icTapToCopy: require('../assets/images/p2p/ic_tap_to_copy.png'),
  icAddPostActive: require('../assets/images/p2p/ic_add.png'),
  icAddPostInactive: require('../assets/images/p2p/ic_add2.png'),
  icAwaitingApproval: require('../assets/images/p2p/ic_waiting_apporval.gif'),
  icApprovalRejected: require('../assets/images/p2p/ic_approval_rejected.gif'),
  //

  icAirport: require('../assets/images/ic_airport.png'),
  icHotel: require('../assets/images/ic_hotel.png'),
  ic_home2NewTab: require('../assets/tabbariconsnew/ic_home2.png'),
  ic_account2NewTab: require('../assets/tabbariconsnew/ic_account2.png'),
  ic_cart2NewTab: require('../assets/tabbariconsnew/ic_cart2.png'),
  ic_celeb2NewTab: require('../assets/tabbariconsnew/ic_celeb2.png'),
  ic_tag2NewTab: require('../assets/tabbariconsnew/ic_tag2.png'),

  //Taxi App new
  ic_down_arrow: require('../assets/images/TaxiAppNew/ic_down_arrow.png'),
  ic_add_location: require('../assets/images/TaxiAppNew/ic_add_location.png'),
  ic_back_taxi: require('../assets/images/TaxiAppNew/ic_back_taxi.png'),
  ic_recent_places: require('../assets/images/TaxiAppNew/ic_recent_places.png'),
  ic_saved_places: require('../assets/images/TaxiAppNew/ic_saved_places.png'),
  ic_bid_ride: require('../assets/images/TaxiAppNew/ic_bid_ride.png'),
  ic_booking: require('../assets/images/TaxiAppNew/ic_booking.png'),
  ic_cab_pooling: require('../assets/images/TaxiAppNew/ic_cab_pooling.png'),
  ic_right_arrow: require('../assets/images/TaxiAppNew/ic_right_arrow.png'),
  ic_close_circle: require('../assets/images/TaxiAppNew/ic_close_circle.png'),

  //Ecommerce Template
  icEcomHome: require('../assets/images/Ecommerce/ic_home_01.png'),
  icEcomHomeInactive: require('../assets/images/Ecommerce/ic_home_02.png'),
  icEcomCart: require('../assets/images/Ecommerce/ic_cart_01.png'),
  icEcomCartInactive: require('../assets/images/Ecommerce/ic_cart_02.png'),
  icRepeat: require('../assets/images/Ecommerce/ic_repeat_02.png'),
  icEcomCeleb: require('../assets/images/Ecommerce/ic_celebrity_01.png'),
  icEcomCelebInactive: require('../assets/images/Ecommerce/ic_celebrity_02.png'),
  icEcomBrand: require('../assets/images/Ecommerce/ic_brand_01.png'),
  icEcomBrandInactive: require('../assets/images/Ecommerce/ic_brand_02.png'),
  icCat: require('../assets/images/Ecommerce/ic_cat.png'),
  icCatActive: require('../assets/images/Ecommerce/ic_cat_active.png'),
  icEcomAccount: require('../assets/images/Ecommerce/ic_account_01.png'),
  icEcomAccountInactive: require('../assets/images/Ecommerce/ic_account_02.png'),
  icEcomHeaderLocation: require('../assets/images/Ecommerce/ic_location_01.png'),
  icEcomDropArrow: require('../assets/images/Ecommerce/ic_downarrow_01.png'),
  icEcomSearch: require('../assets/images/Ecommerce/ic_search_01-1.png'),
  wishlist2: require('../assets/images/Ecommerce/ic_wishlist_01.png'),
  wishlist3: require('../assets/images/Ecommerce/ic_wishlist_03.png'),
  icCart3: require('../assets/images/Ecommerce/ic_cart_03.png'),
  ecomCheck: require('../assets/images/Ecommerce/ic_tickmark_01.png'),
  ecomUnCheck: require('../assets/images/Ecommerce/ic_tickmark_02.png'),
  icCategory: require('../assets/images/Ecommerce/ic_categories_02.png'),
  icPrivacy: require('../assets/images/Ecommerce/ic_privacypolicy_02.png'),
  icTerms: require('../assets/images/Ecommerce/ic_terms&condition_02.png'),
  icHamburger: require('../assets/images/Ecommerce/ic_hamburger_03.png'),
  icEcomCart2: require('../assets/images/Ecommerce/ic_cart_03.png'),
  searchArrow: require('../assets/images/Ecommerce/searchArrow.png'),
  curLangCheck: require('../assets/images/Ecommerce/curLangCheck.png'),
  icLang: require('../assets/images/Ecommerce/ic_language.png'),
  ecomChat: require('../assets/images/Ecommerce/IC_CHAT.png'),
  icCountry: require('../assets/images/Ecommerce/ic_country.png'),
  icCurrency: require('../assets/images/Ecommerce/ic_currency.png'),
  ic_orders2_p2p_inactive: require('../assets/images/Ecommerce/ic_orders2_p2p_inactive.png'),
  ic_orders2_p2p: require('../assets/images/Ecommerce/ic_orders2_p2p.png'),
  ic_chatp2p_active: require('../assets/images/Ecommerce/ic_chatp2p_active.png'),
  ic_chatp2p_inactive: require('../assets/images/Ecommerce/ic_chatp2p_inactive.png'),
  ic_addPostP2p_active: require('../assets/images/Ecommerce/ic_addPostP2p_active.png'),
  ic_addPostP2p_inactive: require('../assets/images/Ecommerce/ic_addPostP2p_inactive.png'),
  icMenuIcon: require('../assets/images/ic_menu.png'),
  locationIcon: require('../assets/images/place.png'),
  ic_notification1: require('../assets/images/ic_notification1.png'),

  //Video
  // flank: require('../assets/flankSplash.mp4'),
  // masa: require('../assets/masa.mp4'),
  // Stabex: require('../assets/stabex.mp4'),
  // muvpod: require('../assets/muvpod.mp4'),
  // parcelWorksSplash: require('../assets/ParcelWorksSplash.mp4'),
  // HezniSplash: require('../assets/HezniSplash.mp4'),
  // 'https://s3.us-west-2.amazonaws.com/royoorders2.0-assets/app_splashscreen/73jvbtlLAQCkDgO58NZ8Zx9tdoOnoxlgNICcS7Gp.mp4',

  // flanksplash: require('../assets/Flanksplash.mp4'),

  // ooryks assets
  Ooryks_logo: require('../assets/images/Ooryks/Ooryks_logo.png'),
  Ooryks_google: require('../assets/images/Ooryks/google_icon.png'),
  ic_map: require('../assets/images/Ooryks/ic_map.png'),
  ic_down_arrow1: require('../assets/images/Ooryks/down_arrow.png'),
  ic_notification: require('../assets/images/Ooryks/ic_notification.png'),
  ic_orders: require('../assets/images/Ooryks/check.png'),
  ic_chat: require('../assets/images/Ooryks/chat.png'),
  ic_account: require('../assets/images/Ooryks/account.png'),
  ic_post: require('../assets/images/Ooryks/post.png'),
  icViewmore: require('../assets/images/Ooryks/icViewmore.png'),
  ic_backarrow: require('../assets/images/Ooryks/ic_backarrow.png'),
  bg_img: require('../assets/images/Ooryks/bg_img.png'),
  ic_right_arrow1: require('../assets/images/Ooryks/ic_rightarrow.png'),
  ic_star: require('../assets/images/Ooryks/Star.png'),
  ooryks_img: require('../assets/images/Ooryks/ooryks_img.png'),
  ooryks_Profile: require('../assets/images/Ooryks/ooryksProfile.png'),
  distance: require('../assets/images/Ooryks/distance.png'),
  Rectangle_checkbox: require('../assets/images/Ooryks/Rectangle_checkbox.png'),
  Info: require('../assets/images/Ooryks/info.png'),
  ic_profile: require('../assets/images/Ooryks/ic_profile.png'),
  ic_mywallet: require('../assets/images/Ooryks/ic_mywallet.png'),
  ic_card: require('../assets/images/Ooryks/ic_card.png'),
  ic_notifiction: require('../assets/images/Ooryks/ic_notifiction.png'),
  ic_help: require('../assets/images/Ooryks/ic_help.png'),
  ic_About: require('../assets/images/Ooryks/ic_About.png'),
  ic_logout: require('../assets/images/Ooryks/ic_logout.png'),
  ic_editpic: require('../assets/images/Ooryks/editpic_ic.png'),
  ic_activeBell: require('../assets/images/Ooryks/ic_activeNotif.png'),
  ic_camPicker: require('../assets/images/Ooryks/ic_camPicker.png'),
  orderItemImg: require('../assets/images/Ooryks/testOrderImgP2P.png'),
  cardTemplate: require('../assets/images/Ooryks/CardTemplateP2P.png'),
  bankAcc1: require('../assets/images/Ooryks/ABank.png'),
  bankAcc2: require('../assets/images/Ooryks/A2Bank.png'),
  icAddPost: require('../assets/images/Ooryks/ic_add_post.png'),
  icAccount: require('../assets/images/Ooryks/ic_account.png'),
  icChat: require('../assets/images/Ooryks/ic_chat.png'),
  icHome: require('../assets/images/Ooryks/ic_home.png'),
  icOrders: require('../assets/images/Ooryks/ic_check.png'),
  icOrdersActive: require('../assets/images/Ooryks/ic_orders_active.png'),
  icChatActive: require('../assets/images/Ooryks/ic_chat_active.png'),
  icBckBtn: require('../assets/images/Ooryks/ic_bck_btn.png'),
  icTick: require('../assets/images/Ooryks/tick.png'),
  icInfoMark: require('../assets/images/Ooryks/info_mark.png'),
  icSearchNew: require('../assets/images/Ooryks/ic_search_new.png'),
  icProfileOrders: require('../assets/images/Ooryks/ic_profile_orders.png'),
  icLocationOrders: require('../assets/images/Ooryks/ic_location.png'),
  icTimeOrders: require('../assets/images/Ooryks/ic_time.png'),
  icArrw: require('../assets/images/Ooryks/ic_arrw.png'),
  icRoute: require('../assets/images/Ooryks/route.png'),
  icHeart: require('../assets/images/Ooryks/heart.png'),
  icPlayVideo: require('../assets/images/play.png'),
  icPauseVideo: require('../assets/images/pause.png'),
  icPdf: require('../assets/images/p2p/pdf.png'),
  icDocx: require('../assets/images/Ooryks/docx.png'),
  icZip: require('../assets/images/Ooryks/zip.png'),
  icXls: require('../assets/images/Ooryks/xls.png'),
  icPpt: require('../assets/images/Ooryks/ppt.png'),
  circleplus: require('../assets/images/Ooryks/circleplus.png'),

  icJcbCard: require('../assets/images/Ooryks/ic_jcb_card.png'),
  icMasterCard: require('../assets/images/Ooryks/ic_master_card.png'),
  icVisaCard: require('../assets/images/Ooryks/ic_visa_card.png'),
  icUnknownCard: require('../assets/images/Ooryks/ic_unknown_card.png'),
  icUnionPay: require('../assets/images/Ooryks/ic_union_pay.png'),
  icDinersClubCard: require('../assets/images/Ooryks/ic_diners_club_card.png'),
  icAmericanExpressCard: require('../assets/images/Ooryks/ic_american_exp.png'),
  icDiscoverCard: require('../assets/images/Ooryks/ic_discover.png'),
  icCardBg: require('../assets/images/Ooryks/card_bg.png'),
  icVideoCamera:require('../assets/images/Ooryks/video-camera.png'),
  icCamera:require('../assets/images/Ooryks/camera.png'),
  ic_filled_star:require('../assets/images/Ooryks/ic_filled_star.png'),
  ic_star_unfill:require('../assets/images/Ooryks/ic_star_unfill.png'),
  ic_location_grey:require('../assets/images/Ooryks/ic_location_grey.png'),
  ic_payment_card:require('../assets/images/Ooryks/ic_payment_card.png'),
  arrow_forward:require('../assets/images/Ooryks/arrow_forward.png'),
  ic_chat_grad_active:require('../assets/images/Ooryks/ic_chat_grad_active.png'),
  ic_chat_grad_inactive:require('../assets/images/Ooryks/ic_chat_grad_inactive.png'),
  ic_orders_grad_active:require('../assets/images/Ooryks/ic_orders_grad_active.png'),
  ic_orders_grad_inactive:require('../assets/images/Ooryks/ic_orders_grad_inactive.png'),
  ic_add_post_grad:require('../assets/images/Ooryks/ic_add_post_grad.png'),
  ic_add_post_grad_inactive:require('../assets/images/Ooryks/ic_add_post_grad_inactive.png'),
  ic_chat4_active:require('../assets/images/Ooryks/ic_chat4_active.png'),
  ic_chat4_inactive:require('../assets/images/Ooryks/ic_chat4_inactive.png'),
  ic_order4_active:require('../assets/images/Ooryks/ic_order4_active.png'),
  ic_order4_inactive:require('../assets/images/Ooryks/ic_order4_inactive.png'),
  ic_add_post4_inactive:require('../assets/images/Ooryks/ic_add_post4.png'),
  ic_add_post4_active:require('../assets/images/Ooryks/ic_add_post4_active.png'),
  ic_order2_inactive:require('../assets/images/Ooryks/ic_order2_active.png'),
  ic_order2_active:require('../assets/images/Ooryks/ic_order2_inactive.png'),
  ic_chat1_active:require('../assets/images/Ooryks/ic_chat1_active.png'),
  ic_chat1_inactive:require('../assets/images/Ooryks/ic_chat1_inactive.png'),
  ic_post1_active:require('../assets/images/Ooryks/ic_post1_active.png'),
  ic_post1_inactive:require('../assets/images/Ooryks/ic_post1_inactive.png'),
  ic_sort_az:require('../assets/images/Ooryks/sort-az.png'),
  
  //atlantic
  loginbanner:require('../assets/images/Atlantic/loginbanner.png'),
   location:require('../assets/images/Atlantic/location.png'),
  logogroup:require('../assets/images/Atlantic/logoGroup.png'),
  oval:require('../assets/images/Atlantic/Oval.png'),
  ic_location_atlantic:require('../assets/images/Atlantic/ic_location_atlantic.png'),
  dotoval:require('../assets/images/Atlantic/dotoval.png'),
  mileage:require('../assets/images/Atlantic/mileage.png'),
  engine:require('../assets/images/Atlantic/engine.png'),
  rightarrow:require('../assets/images/Atlantic/rightarrow.png'),
  yatch:require('../assets/images/Atlantic/Yatch.png'),
  // activeaccount:require('../assets/images/atlantic/activeaccount.png'),
  inactiveaccount:require('../assets/images/Atlantic/inactiveaccount.png'),
  airportactive:require('../assets/images/Atlantic/airportactive.png'),
  airportinactive:require('../assets/images/Atlantic/airportinactive.png'),
  activerent:require('../assets/images/Atlantic/activerent.png'),
  inactiverent:require('../assets/images/Atlantic/inactiverent.png'),
  language:require('../assets/images/Atlantic/language.png'),
  atlantic_notification:require('../assets/images/Atlantic/atlantic_notification.png'),
  notification:require('../assets/images/Atlantic/notification.png'),
  filter_atlantic:require('../assets/images/Atlantic/filter.png'),
  defaultImage:require('../assets/images/Atlantic/default_image.webp'),
  carrentactive:require('../assets/images/Atlantic/carrentactive.png'),
  carrentinactive:require('../assets/images/Atlantic/carrentinactive.png'),
  pickupinactive:require('../assets/images/Atlantic/pickupinactive.png'),
  pickupactive:require('../assets/images/Atlantic/pickupactive.png'),
  yatchactive:require('../assets/images/Atlantic/yatchactive.png'),
  yatchinactive:require('../assets/images/Atlantic/yatchinactive.png'),
  accountactive:require('../assets/images/Atlantic/accountactive.png'),
  locationoval:require('../assets/images/Atlantic/locationoval.png'),
  help:require('../assets/images/Atlantic/help.png'),
  direction:require('../assets/images/Atlantic/direction.png'),
  tickrental:require('../assets/images/Atlantic/tickrental.png'),
  protection:require('../assets/images/Atlantic/protection.png'),
  smart:require('../assets/images/Atlantic/smart.png'),
  additional:require('../assets/images/Atlantic/additional.png'),
  atlanticminus:require('../assets/images/Atlantic/minus.png'),
  atlanticplus:require('../assets/images/Atlantic/plus.png'),
  pricecard:require('../assets/images/Atlantic/pricecard.png'),
  locationatlantic:require('../assets/images/Atlantic/locationatlantic.png'),
  yatchback:require('../assets/images/Atlantic/yatchback.png'),
  calendar:require('../assets/images/Atlantic/calendar.png'),
  dubai:require('../assets/images/Atlantic/dubai.png'),
  cruising:require('../assets/images/Atlantic/cruising.png'),
  yatchimage:require('../assets/images/Atlantic/yatchimage.png'),
  loc_yatch:require('../assets/images/Atlantic/loc_yatch.png'),
  profilepic:require('../assets/images/Atlantic/profilepic.png'),
  banner:require('../assets/images/Atlantic/banner.png'),
  forward:require('../assets/images/Atlantic/forward.png'),
  infodetail: require('../assets/images/Atlantic/infodetail.png'),
  
  atlanticProfile:require('../assets/images/Atlantic/profile.png'),
  suitCase: require('../assets/images/Atlantic/suitCase.png'),
  atlanticChat: require('../assets/images/Atlantic/chat.png'),
  flight: require('../assets/images/Atlantic/flight.png'),
  childSeat: require('../assets/images/Atlantic/child_seat.png'),
  nameSignBoard:require('../assets/images/Atlantic/name_sign_board.png'),
  transmission:require('../assets/images/Atlantic/transmission.png'),
  fule:require('../assets/images/Atlantic/fule.png'),
  seats:require('../assets/images/Atlantic/seats.png'),
  ic_hourly_taxi:require('../assets/images/ic_hourly_taxi.png'),
  ic_hourly_taxi_back:require('../assets/images/ic_hourly_taxi_back.png'),
  ic_minus_hours:require('../assets/images/ic_minus_hours.png'),
  ic_plus_hours:require('../assets/images/ic_plus_hours.png'),
  ic_current_bar:require('../assets/images/ic_current_bar.png'),
  ic_selected_bar:require('../assets/images/ic_selected_bar.png'),
  ic_unselected_bar:require('../assets/images/ic_unselected_bar.png'),
  ic_credit_card:require('../assets/images/credit_card.png'),
  ic_hourly_calendar:require('../assets/images/hourly_calendar.png'),
  ic_hourglass:require('../assets/images/hourglass.png'),
  ic_pickdropcar:require('../assets/images/pickdropcar.png'),
  ic_rentalcar:require('../assets/images/rentalcar.png'),

  // ondemand
  icHomeD: require('../assets/images/OnDemand/home.png'),
  icHomeDInactive: require('../assets/images/OnDemand/Home_inactive.png'),
  icOrderD: require('../assets/images/OnDemand/file.png'),
  icOrderDInactive: require('../assets/images/OnDemand/file_inactive.png'),
  icAccountD: require('../assets/images/OnDemand/profile.png'),
  icAccountDInactive: require('../assets/images/OnDemand/profile2.png'),
  icCartD: require('../assets/images/OnDemand/cart.png'),
  icCartDInactive: require('../assets/images/OnDemand/cart_inactive.png'),

  icArrow2: require('../assets/images/OnDemand/arrow.png'),
  search4: require('../assets/images/OnDemand/search.png'),
  icBackD: require('../assets/images/OnDemand/icBack.png'),
  percentage:require('../assets/images/OnDemand/percentageOD.png'),
  cashOD:require('../assets/images/OnDemand/cashOD.png'),
  servicetype:require('../assets/images/servicetype.png'),
  instructionIcon:require('../assets/images/instructionIcon.png')
};
