export default {
  VENDOR: 'Vendor',
  PRODUCT: 'Product',
  DISPATCHER: 'Dispatcher',
  CATEGORY: 'Category',
  BRAND: 'Brand',
  CELEBRITY: 'Celebrity',
  SUBCATEGORY: 'Subcategory',
  ORDERS: 'Orders',
  PRODUCTS: 'Products',
  REVENUE: 'Revenue',
  ACTIVE: 'active',
  PAST: 'past',
  SCHEDULE: 'schedule',
  PICKUPANDDELIEVRY: 'Pickup/Delivery',
  RETURNREQUEST: 'Return Request',
  ONDEMANDSERVICE: 'On Demand Service',
  VIEW_ALL_VENDORS: 'veiwAllVendors',
  LAUNDRY: 'Laundry',
  APPOINTMENT: 'Appointment',
  RENTAL: 'Rental Service',
  FPX: 'fpx',
  CASH_FREE: 'Cash free',
  FOOD_TEMPLATE: 'Food',
  P2P: 'P2P',
  RENTAL_SERVICE: 'Rental Service',
};
