export { default as HomeCategory6 } from './HomeCategory6';
export { default as HomeCategoryCard2 } from './HomeCategoryCard2';
export { default as HomeCategoryCard_3_5_7 } from './HomeCategoryCard_3_5_7';
export { default as HomeCategoryCard4 } from './HomeCategoryCard4';
export { default as HomeCategoryCard5 } from './HomeCategoryCard5';
export { default as HomeCategoryCard6 } from './HomeCategoryCard6';
// export {default as HomeCategoryCard7} from './HomeCategory7';
export { default as HomeCategoryCard8 } from './HomeCategoryCard8';
export { default as HomeCategoryCardP2p } from './HomeCategoryCardP2p';
export {default as HomeCategoryCard11} from './HomeCategoryCard11';