export default {
  LOGIN: 'login',
  OTP_VERIFICATION: 'OtpVerfication',
  OUTER_SCREEN: 'outerScreen',
  SIGN_UP: 'signUp',
  HOME: 'home',
  HOMESTACK: 'homestack',
  HOME_TEMP_3: 'homeTemplate3',
  OFFERS: 'offers',
  BRANDS: 'brands',
  CATEGORY: 'Category',
  CELEBRITY: 'celebrity',
  ACCOUNTS: 'accounts',
  TAB_ROUTES: 'tabRoutes',
  DRAWER_ROUTES: 'drawerRoutes',
  DELIVERY: 'delivery',
  VENDOR: 'vendor',
  SUPERMARKET: 'supermarket',
  VENDOR_DETAIL: 'VendorDetail',
  PRODUCT_LIST: 'productList',
  MY_PROFILE: 'myProfile',
  MY_ORDERS: 'myOrders',
  ORDER_DETAIL: 'orderDetail',
  ORDER_DETAIL2: 'orderDetail2',
  NOTIFICATION: 'notification',
  ABOUT_US: 'aboutus',
  CONTACT_US: 'contactus',
  TRACKING: 'tracking',
  TRACKDETAIL: 'trackingDetail',
  SEND_PRODUCT: 'sendProduct',
  BUY_PRODUCT: 'buyProduct',
  SHORT_CODE: 'shortCode',
  SETTIGS: 'settings',
  ATTACH_PRINTER: 'AttachPrinter',
  PRODUCTDETAIL: 'productDetail',
  BRANDDETAIL: 'BrandProducts',
  SEARCHPRODUCTOVENDOR: 'SearchProductVendorItem',
  LOCATION: 'Location',
  CART: 'Cart',
  VERIFY_ACCOUNT: 'verifyAccount',
  VERIFY_ACCOUNT_SECOND: 'verifyAccountSecond',
  FORGOT_PASSWORD: 'forgotPassword',
  FILTER: 'filter',
  WISHLIST: 'wishlist',
  WALLET: 'wallet',
  ADD_MONEY: 'addMoney',
  CONFIRM_DETAILS_BUY: 'confirmDetailsBuy',
  PAYMENT: 'payment',
  PAYMENT_SUCCESS: 'paymentSuccess',
  SHIPPING_DETAILS: 'shippingDetails',
  PACKAGE_DETAILS: 'packageDetails',
  CONFIRM_DETAILS_SEND: 'confirmDetailsSend',
  CELEBRITYDETAIL: 'celebrityDetail',
  RESET_PASSWORD: 'resetPassword',
  ALL_PAYMENT_METHODS: 'allPaymentMethod',
  ORDERSUCESS: 'orderSuccess',
  MYSTORES: 'myStores',
  VENDOR_ORDER: 'vendorOrder',
  VENDOR_PRODUCT: 'vendorProduct',
  VENDOR_REVENUE: 'vendorRevenue',
  TABROUTESVENDOR: 'tabRoutesVendor',
  PRODUCTS: 'Products',
  REVENUE: 'Revenue',
  VENDORLIST: 'vendorlist',
  RATEORDER: 'rateorder',
  SENDREFFERAL: 'sendRefferal',
  HOMESCREENCOURIER: 'homeScreenCourier',
  PICKUPLOCATION: 'pickupLocation',
  SETLOACTIONMAP: 'SetLocationInMap',
  CHOOSECARTYPEANDTIME: 'ChooseCarTypeAndTime',
  CABDRIVERLOCATIONANDDETAIL: 'cabDriverLocationTrackAndDetail',
  MULTISELECTCATEGORY: 'multiselectcategory',
  CMSLINKS: 'cmslinks',
  WEBLINKS: 'weblinks',
  WEBPAYMENTS: 'webPayment',
  PICKUPORDERDETAIL: 'pickOrderDetail',
  TRACKORDER: 'trackOrder',
  WEBVIEWSCREEN: 'webViewScreen',
  SUBSCRIPTION: 'subscriptions',
  LOYALTY: 'loyalty',
  CART2: 'orders',
  RETURNORDER: 'returnOrder',
  HOMESCREENTAXI: 'homeScreenTaxi',
  ADDADDRESS: 'addAddress',
  PINADDRESSONMAP: 'pinAddressOnMap',
  PAYMENT_OPTIONS: 'paymentoptions',
  CHOOSECARTYPEANDTIMETAXI: 'ChooseCarTypeAndTimeTaxi',
  OFFERS2: 'OFFERS2',
  PICKUPTAXIORDERDETAILS: 'PickupTaxiOrderDetails',
  PICKUPORDERDETAIL2: 'pickOrderDetail2',
  PRODUCTWITHCATEGORY: 'productWithCategory',

  // royo order

  ROYO_VENDOR_HOME: 'royoHome',
  ROYO_VENDOR_ORDER: 'royoOrder',
  ROYO_VENDOR_BOTTOMTAB: 'royoBottom',
  ROYO_VENDOR_ACCOUNT: 'royoAccount',
  ROYO_VENDOR_PRODUCTS: 'royoProducts',
  ROYO_VENDOR_TRANSACTIONS: 'royoTransactions',
  ROYO_VENDOR_PAYMENT_SETTINGS: 'royoPaymentSettings',
  ROYO_VENDOR_ORDER_DETAIL: 'royoOrderDetail',
  ROYO_VENDOR_ADD_PRODUCT: 'royoAddProduct',
  VIEW_ALL_DATA: 'viewAllData',
  TAXIHOMESCREEN: 'taxiHomeScreen',
  TAXITABROUTES: 'taxiTabRoutes',
  MOBBEX: 'mobbex',
  PAYFAST: 'payfast',
  APP_INTRO: 'app_intro',
  YOCO: 'yoco',
  TIP_PAYMENT_OPTIONS: 'tipPaymentOptions',
  PAYLINK: 'paylink',
  ADD_VEHICLE_DETAILS: 'addVehicleDetails',
  CATEGORY_BRANDS: 'categoryBrands',
  ALL_IN_ONE_PAYMENTS: 'allInOnePayments',
  CART_SCREEN: 'cartScreen',
  SIMPLIFY: 'simplify',
  SQUARE: 'square',
  PAGARME: 'pagarme',
  INVENTORY: 'inventory',
  ADD_PRODUCT: 'addProduct',
  PAYSTACK: 'paystack',
  SCROLLABLE_CATEGORY: 'ScrollableCategory',
  TABROUTESVENDORNEW: 'TabRoutesVendorNewTemplate',
  AuthorizeNet: 'AuthorizeNet',
  FPX: 'fpx',
  KONGOPAY: 'KongoPay',
  AVENUE: 'Avenue',
  CASH_FREE: 'cashFree',
  MYORDERSSTACK: 'myOrdersStack',
  EASEBUZZ: 'easebuzz',
  TOYYIAPAY: 'toyyibPay',
  MPAISA: 'Mpaisa',
  WINDCAVE: 'WindCave',
  PAYPHONE: 'PayPhone',
  ADD_NEW_RIDER: 'AddNewRider',
  STRIPEOXXO: 'StripeOXXO',
  VIVAWALLET: 'Vivawallet',
  MYCASH: 'MyCash',
  STRIPEIDEAL: 'StripeIdeal',
  OPENPAY: 'openpay',
  USEREDE: 'userede',
  LAUNDRY_AVAILABLE_VENDORS: 'laundryAvailableVendors',
  CHAT_SCREEN: 'ChatScreen',
  CHAT_ROOM: 'chatRoom',
  DIRECTPAYONLINE: 'DirectPayOnline',
  KHALTI: 'Khalti',
  SUBCATEGORY_VENDORS: 'subcategoryVendors',
  SEARCH: 'Search',
  CHAT_SCREEN_FOR_VENDOR: 'chatScreenForVendor',
  CHAT_ROOM_FOR_VENDOR: 'chatRoomForVendor',
  CONEKTA: 'conekta',
  VERIFY_ACCOUNT_TAXI: 'VerifyAccountTaxi',
  VERIFY_ACCOUNT_COURIER: 'VerifyAccountCourier',
  ORDER_TRACKING: 'OrderTracking',
  POST: 'Post',
  POST_CATEGORY: 'PostCategory',
  P2P_PRODUCTS: 'p2pProducts',
  ATTRIBUTE_INFORMATION: 'attributeInformation',
  P2P_PRODUCT_DETAIL: 'p2pProductDetail',
  REPLACE_ORDER: 'replaceOrder',
  CHAT_STACK: 'chatStack',
  MY_POSTS: 'myPosts',
  REFER_AND_EARN: 'referAndEarn',
  PLUGNPAY: 'PlugnPay',
  SPOTDEALPRODUCTSANDSELECTEDPRODUCTS: 'SpotdealProductAndSelectedProducts',
  BIDINGDRIVERSLIST: 'BidingDriversList',
  SAVEDCARDS: 'SavedCards',
  SKIP_CASH: 'SkipCash',
  VIEW_ALL_SEARCH_ITEM: 'ViewAllSearchItems',
  ORDER_AGAIN: 'OrderAgain',
  ECOM_LANG_CURRENCY: 'EcomLangCurrency',
  FREELANCER_SERVICE: 'freelancerService',
  AVAILABLE_TECHNICIANS: 'availableTechnicians',
  TECHNICIAN_PROFILE: 'technicianProfile',
  PESAPAL: 'Pesapal',
  PAYMENT_SCREEN: 'paymentScreen',
  P2P_ORDER_STACK: 'p2pOrderStack',
  RENT_TYPE_LISTING: 'rentTypeListing',
  P2P_ORDER_DETAIL: 'p2pOrderDetail',
  ALL_CATEGORIES: 'allCategories',
  PRODUCT_PRICE_DETAILS: 'productPriceDetails',
  DEVELOPER_MODE: 'DeveloeprMode',
  PRODUCT_POWER_CONSUMPTION: 'ProductPowerConumption',
  LIVESS: 'Livees',
  SAVED_PAYMENT_CARDS:"savedPaymentCards",
  // car rental stacks
  CAR_RENTAL_HOME:'CarRentalHome',
  AVAILABLE_CARS:'AvailableCar',
  REVIEW_BOOKING:'ReviewBooking',
  ALL_VENDOR_ON_DEMAND:"allVendorOnDemand",
  ONLY_PRODUCT_OD:'OnlyProductOD',
  ONLY_CATEGORY_OD:'OnlyCategoryOD',
  PRODUCT_WITH_CATEGORY_OD:'ProductWithCategoryOD',
  PRODUCT_WITH_EXTENDED_CATEGORY:'ProductWithCategoryExtendedOD',
  OFFERSONDEMAND:'OffersOnDemand',
  PAYPAL:'Paypal',
  OPAY:'Opay',
  MASTERCARD:'MaserCard',
  HITPAY:'HitPay'
};
