import { StyleSheet } from 'react-native';
import colors from '../../styles/colors';
import {
  height,
  moderateScale,
  moderateScaleVertical,
  textScale,
  width,
} from '../../styles/responsiveSize';

export default ({ themeColors, fontFamily }) => {
  const styles = StyleSheet.create({
    modalContainer: {
      backgroundColor: colors.white,
      // position: 'absolute',
      // left: 0,
      // right: 0,
      // bottom: 0,
      // top: height - height / 3,
      borderRadius: moderateScale(25),
      overflow: 'hidden',

      // paddingBottom: moderateScaleVertical(30),
      height: height / 3.5,
      // maxHeight: height / 2,
      width: width,
    },
    absolute: {
      position: 'absolute',
      alignItems: 'center',
      justifyContent: 'center',
      height: moderateScaleVertical(30),
      top: 0,
      left: 0,
      bottom: 0,
      right: 0,
      borderRadius: moderateScaleVertical(15),
    },
    topLogo: {
      justifyContent: 'center',
      alignItems: 'flex-start',
      // paddingTop: moderateScaleVertical(12),
      paddingBottom: moderateScaleVertical(12),
      paddingLeft: moderateScaleVertical(12),
    },
    imgSmall: { height: '100%', width: '100%', borderRadius: 4 },
    imgContainer: {
      height: moderateScaleVertical(128),
      width: width * 0.5 - moderateScale(12),
      borderRadius: 4,
      marginBottom: moderateScale(8),
    },
    imgOverlay: {
      ...StyleSheet.absoluteFillObject,
      borderRadius: 4,
      backgroundColor: 'rgba(0,0,0,0.3)',
    },
    blurContainer: {
      position: 'absolute',
      left: moderateScale(115),
      bottom: 10,
      alignItems: 'center',
      justifyContent: 'center',
      right: moderateScale(115),
      // backgroundColor: 'rgba(255,255,255,.35)',
      borderRadius: moderateScaleVertical(15),
      height: moderateScaleVertical(30),
      overflow: 'hidden',
    },
    txt: {
      color: colors.white,
      fontFamily: fontFamily.bold,
      opacity: 0.9,
    },
    absolute: {
      position: 'absolute',
      alignItems: 'center',
      justifyContent: 'center',
      height: moderateScaleVertical(30),
      top: 0,
      left: 0,
      bottom: 0,
      right: 0,
      borderRadius: moderateScaleVertical(15),
    },
    columnBox: {
      flexDirection: 'row',
      flexWrap: 'wrap',
      marginHorizontal: moderateScale(8),
      justifyContent: 'space-between',
      marginTop: moderateScaleVertical(8),
    },
    verticalRectBox: {
      marginHorizontal: moderateScale(8),
      marginTop: moderateScale(8),
      flexDirection: 'row',
      justifyContent: 'space-between',
    },
    rectangleBox: {
      height: width * 0.32,
      width: width * 0.96,
      // height: moderateScaleVertical(128),
      marginHorizontal: moderateScale(8),
      // width: width - moderateScale(16),
      borderRadius: 4,
    },
    cardViewStyle: {
      alignItems: 'center',
      height: 180,
      width: width - 20,
      marginHorizontal: moderateScale(10),
      // marginRight: 20
    },
    searchBarLogo: {
      justifyContent: 'center',
      // flex: 0,
      alignItems: 'flex-end',
      // paddingTop: moderateScaleVertical(12),
      paddingBottom: moderateScaleVertical(12),
      paddingRight: moderateScaleVertical(12),
      flexDirection: 'row',
      alignItems: 'center',
    },
    address: {
      paddingLeft: 2,
      // height:20,
      lineHeight: 20,
      fontFamily: fontFamily.regular,
      color: colors.blackOpacity66,
      fontSize: textScale(12),
      textAlign: 'left',
    },
    addressTitle: {
      paddingLeft: 2,
      // height:20,
      lineHeight: 20,
      fontFamily: fontFamily.regular,
      color: colors.black,
      fontSize: textScale(13),
      textAlign: 'left',
    },

    mainView: {
      flex: 1,
    },
    sheetContent: {
      height: '100%',
      backgroundColor: colors.white,
    },
    header: {
      backgroundColor: colors.white,
      shadowColor: colors.black,
      borderTopLeftRadius: 20,
      borderTopRightRadius: 20,
    },
    panelHeader: {
      alignItems: 'center',
    },
    panelHandle: {
      width: moderateScale(45),
      height: moderateScaleVertical(5),
      borderRadius: 4,
      backgroundColor: colors.greyLight,
      marginVertical: moderateScaleVertical(12),
    },

    container: {
      height: moderateScale(height / 2),
      width: width,
      justifyContent: 'center',
      alignItems: 'center',
    },
    circularView: {
      height: moderateScale(width / 3.8),
      width: moderateScale(width / 3.8),
      borderWidth: 10,
      borderColor: colors.borderColorc,
      borderRadius: moderateScale(width / 7.5),
      alignItems: 'center',
      justifyContent: 'center',
    },
    categoryText: {
      color: colors.textGreyH,
      fontSize: textScale(10),
    },
    circularListCenterImage: {
      position: 'absolute',
    },

    container1: {
      justifyContent: 'center',
      alignItems: 'center',
    },
    circularView: {
      height: moderateScale(width / 4),
      width: moderateScale(width / 4),
      borderWidth: 5,
      borderColor: colors.borderColorc,
      borderRadius: moderateScale(width / 8),
      alignItems: 'center',
      justifyContent: 'center',
    },
    categoryText: {
      color: colors.textGreyH,
      fontSize: textScale(9),
      textAlign: 'left',
    },
    circularListImage: { height: moderateScale(40), width: moderateScale(40) },
    applyPromoBtn: {
      marginHorizontal: moderateScale(7),
      borderRadius: moderateScale(15),
      borderWidth: 1.5,
      borderColor: colors.borderColorD,
      paddingVertical: moderateScaleVertical(15),
      paddingHorizontal: moderateScaleVertical(10),
      marginVertical: moderateScaleVertical(20),
      flexDirection: 'row',
      justifyContent: 'center',
      alignItems: 'center',
    },
    nearVendorTxt: {
      fontFamily: fontFamily.bold,
      fontSize: textScale(16),
      marginBottom: moderateScale(25),
      marginLeft: moderateScale(5),
    },
    viewAllBtn: {
      fontFamily: fontFamily.medium,
      fontSize: textScale(14),
      color: themeColors.primary_color,
    },
    greetingMsg: {
      fontFamily: fontFamily.bold,
      fontSize: textScale(17),
      marginHorizontal: moderateScale(6),
      marginBottom: moderateScaleVertical(5),
    },
    heyMsg: {
      fontFamily: fontFamily.bold,
      fontSize: textScale(17),
      marginTop: moderateScale(15),
      marginHorizontal: moderateScale(6),
      textAlign: 'left',
    },
    modalMainViewContainer: {
      backgroundColor: colors.white,
      borderTopLeftRadius: moderateScale(15),
      borderTopRightRadius: moderateScale(15),
      maxHeight: height - width / 2,
      minHeight: height / 4,
      paddingHorizontal: moderateScale(10),
      justifyContent: 'center',
    },

    headerContainer: {
      flexDirection: 'row',
      justifyContent: 'space-between',
      paddingHorizontal: moderateScale(15),
      marginTop: moderateScale(5),
      alignItems: 'center',
      // borderBottomWidth: 0.8,
      paddingBottom: moderateScale(5),
    },
    locationIcon: {
      height: moderateScale(18),
      width: moderateScale(18),
      tintColor: themeColors.primary_color,
      marginRight: moderateScale(2)
    },
    locationTxt: {
      paddingLeft: 5,
      lineHeight: 20,
      fontFamily: fontFamily.regular,
      color: colors.textGrey,
      fontSize: textScale(12),
      textAlign: 'left',
    },
    deliveryIcon: {
      width: moderateScale(18),
      height: moderateScale(18),
      tintColor: themeColors.primary_color,
    },
    checkedTxt: {
      fontFamily: fontFamily.regular,
      color: themeColors.primary_color,
      marginHorizontal: moderateScale(3),
      textAlign: 'left',
      fontSize: textScale(12),
    },
    customDropDownIcon: {
      width: moderateScale(8),
      height: moderateScale(8),
      tintColor: themeColors.primary_color,
      marginTop: moderateScaleVertical(3),
    },
    closeButton: {
      alignSelf: 'center',
      height: moderateScaleVertical(30),
      marginBottom: moderateScale(15),
    },
    crossIcon: {
      height: moderateScale(35),
      width: moderateScale(35),
    },
    searchBar: {
      flexDirection: 'row',
      height: moderateScaleVertical(50),
      backgroundColor: colors.greyNew,
      borderRadius: moderateScale(15),
      paddingHorizontal: moderateScale(15),
      alignItems: 'center',
      justifyContent: 'space-between',
      marginHorizontal: moderateScale(15),
      marginVertical: moderateScale(13),
    },
    exploreStoresTxt: {
      fontFamily: fontFamily.bold,
      fontSize: textScale(14),
      textAlign: 'left',
    },
    dotStyle: {
      height: 6,
      width: 18,
      borderRadius: 12 / 2,
      marginLeft: -8,
    },
    inActiveDotStyle: {
      height: 8,
      width: 8,
      borderRadius: 4,
      marginLeft: -8,
    },
    blurView: {
      position: 'absolute',
      alignItems: 'center',
      justifyContent: 'center',
      height: '100%',
      top: 0,
      left: 0,
      bottom: 0,
      right: 0,
      borderRadius: moderateScaleVertical(15),
    },

    blurViewHome: {
      position: 'absolute',
      alignItems: 'center',
      justifyContent: 'center',
      top: 0,
      left: 0,
      bottom: 0,
      right: 0,
    },
    toolTipStyle: {
      height: moderateScale(8),
      backgroundColor: themeColors.primary_color,
      alignItems: 'center',
      width: moderateScale(30),
      borderRadius: moderateScale(10),
      alignSelf: 'center',
      marginVertical: moderateScale(10),
    },
    viewAllText: {
      color: themeColors.primary_color,
      fontFamily: fontFamily.medium,
      fontSize: textScale(12),
    },
    viewAllVeiw: {
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'space-between',
      marginHorizontal: moderateScale(16),
      marginVertical: moderateScaleVertical(15),
    },
    menuView: {
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'center',
      borderRadius: moderateScale(4),
      borderWidth: 0.3,
      borderColor: colors.textGreyB,
      padding: moderateScale(6),
    },
    hdrRatingTxtView: {
      flexDirection: 'row',
      alignItems: 'center',
      backgroundColor: colors.green,
      paddingVertical: moderateScale(2),
      paddingHorizontal: moderateScale(4),
      alignSelf: 'flex-start',
      borderRadius: moderateScale(2),
      marginTop: moderateScaleVertical(16),
    },
    ratingTxt: {
      // color: colors.yellowC,
      // fontSize: textScale(11),
      fontFamily: fontFamily.medium,
      textAlign: 'left',
      color: colors.white,
      fontSize: textScale(9),
    },
    starImg: {
      tintColor: colors.white,
      marginLeft: 2,
      width: 9,
      height: 9,
    },
    locationTitleTxt: {
      fontFamily: fontFamily.medium,
      fontSize: moderateScale(13),
    },
    locationTxt: {
      fontFamily: fontFamily.medium,
      fontSize: moderateScale(12),
      marginLeft: 2,
    },
    locationView: {
      marginLeft: 5,
    },
    locationTypeTxt: {
      fontFamily: fontFamily.bold,
      fontSize: moderateScale(15),
      marginLeft: 2,
      color: themeColors.primary_color,
    },
    modal: {
      margin: 0,
      alignItems: 'center',
    },
    modalContainer: {
      backgroundColor: '#fff',
      paddingHorizontal: 16,
      paddingTop: 20,
      paddingBottom: 40,
      alignItems: 'center',
      width: width - 50,
      borderRadius: 12,
    },
    horizontalLine: {
      marginVertical: moderateScaleVertical(15),
      width: '70%',
    },
    ageModalText: {
      fontFamily: fontFamily.bold,
      fontSize: textScale(15),
    },
    ageConfirmationText: {
      marginBottom: moderateScale(10),
      fontFamily: fontFamily.regular,
      fontSize: textScale(14),
      textAlign: 'center',
    },
    takeMeOutStyle: {
      textAlign: 'center',
      color: themeColors.primary_color,
      fontFamily: fontFamily.regular,
      fontSize: textScale(12),
      marginTop: moderateScaleVertical(10),
    },
    innerAgeModaleView: {
      paddingVertical: moderateScaleVertical(15),
      paddingHorizontal: moderateScale(10),
      backgroundColor: 'white',
      borderRadius: 15,
      width: width / 1.2,
      minHeight: moderateScaleVertical(150),
      alignItems: 'center',
      shadowColor: '#000',
      shadowOffset: {
        width: 0,
        height: 2,
      },
      shadowOpacity: 0.25,
      shadowRadius: 4,
      elevation: 5,
    },
    searchBarView: {
      flexDirection: 'row',
      paddingHorizontal: moderateScale(16),
      height: moderateScaleVertical(48),
      backgroundColor: colors.lightGray,
      alignItems: 'center',
      justifyContent: 'space-between',
      borderRadius: moderateScale(10),
      marginHorizontal: moderateScale(10),
      marginVertical: moderateScaleVertical(10),
    },
  });

  return styles;
};
